# package NUMPY

In [1]:
import numpy as np #import le package numpy 


#---------------------------------------Rules of Broadcasting-------------------------------------------------

# Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

# • Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

# • Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

# • Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [2]:
np.array([1,2,3]) #cree une vecteur de 3 colomn

array([1, 2, 3])

In [3]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]]) #cree une matrice de taille 3x3
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A.shape # donner la taille du matrice

(3, 3)

In [5]:
A.size # donner le nombre d'element dans cette matrice

9

In [6]:
A.ndim # donner le dimention de cette matrice

2

In [7]:
B=np.zeros((3,3)) #cree une matrice de taille 3x3 avec tous les valeurs sont des 0
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
B=np.ones((3,3)) #cree une matrice de taille 3x3 avec tous les valeurs sont des 1
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b=np.full((3,3),5) #cree une matrice de taille 3x3 avec tous les valeurs sont des 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
np.random.randn(2,3) #cree une matrice random de taille 2x3 

array([[-2.09341892, -0.82622086, -0.65023049],
       [-0.2298033 , -1.23661341, -1.90943473]])

In [11]:
np.eye(4) # cree une matrice identite 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linspace(0,10,20,dtype=int) # cree une vecteur debut par 0 et fin par 10 et de 20 elements ,dtype pour changer le type du variable

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

In [13]:
np.arange(0,10,2) # cree une vecteur debut par 0 et fin par 10 et avec un pas de 2

array([0, 2, 4, 6, 8])

In [14]:
A=np.zeros((3,3))
B=np.ones((3,3))
np.vstack((A,B)) # concatene deux matrice verticalement 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.hstack((A,B))  # concatene deux matrice horiztalement

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [16]:
np.concatenate((A,B),axis=0) # comme vstack 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.concatenate((A,B),axis=1) # comme hstack (concatenate est plus mieux que les autres car on peux concatene des matrice dans l 3eme dim si on donne a axis la valeur 2)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [18]:
b=np.linspace(0,10,10)
b

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [19]:
np.shape(b)

(10,)

In [20]:
b.reshape((10,1)) # changer le shape du matrice (le nombre des elements doit etre toujours la meme)

array([[ 0.        ],
       [ 1.11111111],
       [ 2.22222222],
       [ 3.33333333],
       [ 4.44444444],
       [ 5.55555556],
       [ 6.66666667],
       [ 7.77777778],
       [ 8.88888889],
       [10.        ]])

In [21]:
np.shape(b)
np.squeeze(b)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
A.ravel() # convertir une matrice a une  vecteur

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
C=np.array([2,4,6,1,2,5,8,2,23,213,5,2,66234,23,65,7,573]) 
C<5 #si c[i]<5 donne true sinon donne false

array([ True,  True, False,  True,  True, False, False,  True, False,
       False, False,  True, False, False, False, False, False])

In [24]:
C[C<5]=9999 # si c[i] < 5 => c[i]=9999

In [25]:
C

array([ 9999,  9999,     6,  9999,  9999,     5,     8,  9999,    23,
         213,     5,  9999, 66234,    23,    65,     7,   573])

In [26]:
np.random.seed(0)
array=np.random.randint(0,100,[5,5])
array

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72]])

In [27]:
array.sum()# sommer les elements du matrice

1458

In [28]:
array.sum(axis=0) #sommer les elements de chaque ligne

array([269, 294, 285, 238, 372])

In [29]:
array.sum(axis=1) # sommer les elements de chaque column

array([289, 236, 316, 325, 292])

In [30]:
array.min() # donner le min

9

In [31]:
array.max() # donner le max

88

In [32]:
array.min(axis=0) # donner le max de chaque

array([ 9, 37, 21, 12, 58])

In [33]:
array.argmin() #donner l'indece du min

5

In [34]:
np.sort(array,axis=0) # trier les elements du matrice pour chaque ligne

array([[ 9, 37, 21, 12, 58],
       [44, 39, 25, 36, 67],
       [65, 47, 64, 46, 72],
       [70, 83, 87, 67, 87],
       [81, 88, 88, 77, 88]])

In [35]:
np.argsort(array,axis=0)

array([[1, 4, 1, 2, 2],
       [0, 3, 4, 1, 0],
       [3, 0, 0, 3, 4],
       [2, 1, 3, 0, 1],
       [4, 2, 2, 4, 3]], dtype=int64)

In [36]:
np.exp(array) # calculer exp de chaque element

array([[1.28516001e+19, 2.58131289e+20, 6.23514908e+27, 1.25236317e+29,
        1.25236317e+29],
       [8.10308393e+03, 1.11286375e+36, 1.31881573e+09, 4.31123155e+15,
        6.07603023e+37],
       [2.51543867e+30, 1.65163625e+38, 1.65163625e+38, 1.62754791e+05,
        1.54553894e+25],
       [1.69488924e+28, 8.65934004e+16, 6.07603023e+37, 9.49611942e+19,
        1.65163625e+38],
       [1.50609731e+35, 1.17191424e+16, 7.20048993e+10, 2.75851345e+33,
        1.85867175e+31]])

In [37]:
np.log(array) # calculer log de chaque elemente

array([[3.78418963, 3.8501476 , 4.15888308, 4.20469262, 4.20469262],
       [2.19722458, 4.41884061, 3.04452244, 3.58351894, 4.46590812],
       [4.24849524, 4.47733681, 4.47733681, 2.48490665, 4.06044301],
       [4.17438727, 3.66356165, 4.46590812, 3.8286414 , 4.47733681],
       [4.39444915, 3.61091791, 3.21887582, 4.34380542, 4.27666612]])

In [38]:
A=np.random.randint(0,100,[4,4])
A

array([[ 9, 20, 80, 69],
       [79, 47, 64, 82],
       [99, 88, 49, 29],
       [19, 19, 14, 39]])

In [39]:
A.mean() # moyenne des elements du tableua

50.375

In [40]:
A.std() # ecart-type du matrice

29.085810543974876

In [41]:
A.var() # variance du matrice

845.984375

In [42]:
np.corrcoef(A) # donner la corr de chaque deux ligne

array([[ 1.        ,  0.19150629, -0.92884189,  0.26678056],
       [ 0.19150629,  1.        , -0.34717639,  0.56154525],
       [-0.92884189, -0.34717639,  1.        , -0.60353566],
       [ 0.26678056,  0.56154525, -0.60353566,  1.        ]])

In [43]:
np.count_nonzero(A) # count les elements qui sont non-null

16

In [44]:
np.unique(A,return_counts=True) # count la repetition de chaque element

(array([ 9, 14, 19, 20, 29, 39, 47, 49, 64, 69, 79, 80, 82, 88, 99]),
 array([1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [45]:
B=np.corrcoef(A)

In [46]:
B[1:-1,1:-1]=np.nan # donner a les valeur qui sont a  l'intreir la valeur nan(not a number)
B

array([[ 1.        ,  0.19150629, -0.92884189,  0.26678056],
       [ 0.19150629,         nan,         nan,  0.56154525],
       [-0.92884189,         nan,         nan, -0.60353566],
       [ 0.26678056,  0.56154525, -0.60353566,  1.        ]])

In [47]:
np.nanmean(B) # calcule moyenne et ingore le nan

0.08124242497516038

In [48]:
np.nanstd(B) # calcule std et ingore le nan

0.6596185957855655

In [49]:
np.nanvar(B)  # calcule var et ingore le nan

0.4350966919061212

In [50]:
np.isnan(B) # retourn true if l'element is nan

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [51]:
B[np.isnan(B)]=0 # donner a les elements qui sont nan la valeur 0

In [52]:
B

array([[ 1.        ,  0.19150629, -0.92884189,  0.26678056],
       [ 0.19150629,  0.        ,  0.        ,  0.56154525],
       [-0.92884189,  0.        ,  0.        , -0.60353566],
       [ 0.26678056,  0.56154525, -0.60353566,  1.        ]])

In [53]:
A

array([[ 9, 20, 80, 69],
       [79, 47, 64, 82],
       [99, 88, 49, 29],
       [19, 19, 14, 39]])

In [54]:
A.T #transpose de la matrice A

array([[ 9, 79, 99, 19],
       [20, 47, 88, 19],
       [80, 64, 49, 14],
       [69, 82, 29, 39]])

In [55]:
np.linalg.inv(A) #inverse du matrice A

array([[-0.01399462,  0.02825304, -0.0052762 , -0.03072078],
       [ 0.00875146, -0.03458426,  0.01845113,  0.04351221],
       [ 0.01402608,  0.00406624,  0.00219703, -0.03499859],
       [-0.00248064,  0.00162477, -0.00720723,  0.0319729 ]])

In [56]:
np.linalg.det(A) #ditermenet du matrice A

6357227.000000005

In [57]:
np.linalg.eig(A) #retourn les valeurs et les vecteur propre

(array([197.30538137,  24.73403476, -53.84770139, -24.19171474]),
 array([[-0.41160526, -0.21180514, -0.80049679,  0.71093995],
        [-0.59735193,  0.20160524,  0.26179694, -0.68775711],
        [-0.66438318, -0.67570659,  0.53835178, -0.14465697],
        [-0.17985207,  0.67669381,  0.02906235,  0.02507803]]))

In [58]:
a=np.arange(1,5,1)
a

array([1, 2, 3, 4])

In [59]:
np.multiply.outer(a,a) # matrice a.T * a

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [60]:
np.count_nonzero(a)

4

In [61]:
np.all(a<3) # retourn true if tous les elements sont inferieur a 3

False

In [62]:
np.any(a<3) #retourn true if un element est inferieur a 3

True

In [63]:
np.info(np.partition) # donner comment une methode travaille

 partition(a, kth, axis=-1, kind='introselect', order=None)

Return a partitioned copy of an array.

Creates a copy of the array with its elements rearranged in such a
way that the value of the element in k-th position is in the
position it would be in a sorted array. All elements smaller than
the k-th element are moved before this element and all equal or
greater are moved behind it. The ordering of the elements in the two
partitions is undefined.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to be sorted.
kth : int or sequence of ints
    Element index to partition by. The k-th value of the element
    will be in its final sorted position and all smaller elements
    will be moved before it and all equal or greater elements behind
    it. The order of all elements in the partitions is undefined. If
    provided with a sequence of k-th it will partition all elements
    indexed by k-th  of them into their sorted position at once.
axis : int or None, optional

In [64]:
b=np.copy(a) # copy un matrice

In [65]:
b

array([1, 2, 3, 4])

In [66]:
print(b.base) # voir si un matrice est basee d'un autre matrice (c-a-d si on change dans b ,dans copy a ne change pas )

None


In [67]:
b=a.view( ) # view comme copy mais view est basee a une autre matrice

In [68]:
b

array([1, 2, 3, 4])

In [69]:
b.base

array([1, 2, 3, 4])

In [70]:
a

array([1, 2, 3, 4])

In [71]:
np.append(a,[1,22,33,4])

array([ 1,  2,  3,  4,  1, 22, 33,  4])

In [72]:
A=np.array([[1,2,3],[1,2,3]])
A=np.append(A,[[5,6,7]],axis=0)

In [73]:
np.delete(A,1,axis=1) # delete un column(axis=1) ou un ligne(axis=0)

array([[1, 3],
       [1, 3],
       [5, 7]])

In [74]:
np.split(A,3) # decomposer matrice A a trois matrice

[array([[1, 2, 3]]), array([[1, 2, 3]]), array([[5, 6, 7]])]

In [75]:
A=np.arange(0,10,1)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.add(A,2) # ajouter a tous les  elements la valuer 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
np.multiply(A,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
np.power(A,10)

array([         0,          1,       1024,      59049,    1048576,
          9765625,   60466176,  282475249, 1073741824, -808182895],
      dtype=int32)

In [79]:
np.subtract(A,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [80]:
np.divide(A,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [81]:
A=np.random.randint(0,10,[5,5])
B=np.random.randint(0,10,[5,5])
A.dot(B)# multiplycation matriciel 

array([[124,  65,  72,  93, 113],
       [140,  89, 105,  94, 122],
       [ 50,  45,  69,  47,  69],
       [169, 104, 100, 102, 129],
       [171,  92,  79,  96, 114]])

In [82]:
np.array_equal(A,B) # retourn True si les deux matrice sont egaux

False

In [83]:
A2=np.array([3,3,4])
B2=np.array([[3,0,-1],[0,1,0],[3,0,-1]])

In [84]:
A2*B2

array([[ 9,  0, -4],
       [ 0,  3,  0],
       [ 9,  0, -4]])

In [85]:
np.multiply( B,B )

array([[49, 81, 81,  9, 36],
       [49,  4,  0,  9, 25],
       [81, 16, 16, 36, 16],
       [16,  9, 16, 16, 64],
       [16,  9, 49, 25, 25]])